#small tree, 3habits, 1 checkin per habit,  active

[metadata]
name=Small3HabitTree
seed=1

[habits_tracker]
num_habits=3
habit_name_length=10
habit_desc_length=20

[habit]
checkins_no=1
archived_chance=0

[checkin]
active_chance=100
sequential_chance=100
